# Site settings
title: "She codes"
header-img: img/home-bg.png
email: sakht318@gmail.com
copyright_name: sakhtar1
description: > # this means to ignore newlines until "baseurl:"
  01010011 01101000 01100101 00100000 01000011 01101111 01100
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sakhtar1
learn_profile: sakhtar1
email_username: sakht318@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
