# Site settings
author: Sharmina Akhtar
title: "She codes"
header-img: img/home-bg.png
email: sakht318@gmail.com
copyright_name: Sharmina Akhtar
description: > # this means to ignore newlines until "baseurl:"
  Digital Nomad | Globe Trotter | Builder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sakhtar1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
